### ISSUE TITLE
User rate limit exceeded

### ISSUE THREAD

**Issue by seadog007** [google/skicka#100]
After I uploaded about 700GB data, then my skicka appear this message.
<img width="1280" alt="2016-01-23 2 23 13" src="https://cloud.githubusercontent.com/assets/5138409/12528770/e57d2ea2-c1dc-11e5-8105-3e00e0eb50a6.png">

**Comment by mmp** [comment]
This can occasionally happen--there's a balance between making Drive API requests quickly to get the transfer done efficiently versus making too many, such that it issues those errors.

It should retry a few times (after waiting a bit) when errors like that are issued. To be sure, re-run the skicka upload command and it will try again for any files that weren't transferred the first time.
