### ISSUE TITLE
Add dry-run mode (like rsync -n)

### ISSUE THREAD

**Issue by agoode** [google/skicka#101]
Having a dry-run mode is useful in verifying a command before running it. It is also helpful when deleting files: dry run can allow you to delete locally, then do a dry-run download to see what to delete remotely.

**Comment by mmp** [comment]
Done. Let me know if you have any comments/suggestions about the formatting.

Note that the files are printed to stdout but regular logging stuff goes to stderr, so it should be fairly easy to extract / munge as needed.
