### ISSUE TITLE
Remove all photos

### ISSUE THREAD

**Issue by maauso** [google/skicka#103]
Hi 

Is it possible use skicka for remove all my google photos?

thanks

**Comment by mmp** [comment]
I've dug into this a bit. In general, when an app uses Google Drive for storage but creates hidden app-specific files (as Google Photos does), then it seems that it's not possible for anything other than the app that created those files to see them (see e.g. http://webapps.stackexchange.com/questions/73940/how-can-i-see-hidden-files-in-google-drive).

However, if you look at the instructions under "Organize photos and videos using Google Drive" at https://support.google.com/photos/answer/6156103?hl=en, it seems that there is a way to make your photos visible in a folder in Drive, which presumably could be managed (or deleted) by skicka.

Now, I'm not sure if that folder would mirror your photos, or if deleting it would also delete the photos. If you try this, let me know how it goes!

**Comment by maauso** [comment]
Hi Matt

Thanks for your reply, I tried remove photos through google drive, but this
folder is not listing with skicka, so you can't remove.

Personally, I think that it's a problem, because it easy upload your
photos, but it's hard if you want leave the service

Thanks

**Comment by mmp** [comment]
If you want to download all of your photos, https://takeout.google.com/settings/takeout should make that fairly easy.

**Comment by maauso** [comment]
Yes, it's true, but the main problem is if you want remove all photos, you
don't have easy way to do it

**Comment by mmp** [comment]
Closing since this isn't anything skicka can help with, unfortunately.
