### ISSUE TITLE
"go get" fails due to removal of googleapi.SetOpaque

### ISSUE THREAD

**Issue by chschu** [google/skicka#107]
The function `googleapi.SetOpaque()` has been removed with commit google/google-api-go-client@845dfb517ad661ea71fe13c6ac224baaadc78bfd. Since then, `go get github.com/google/skicka` fails:

```
# github.com/google/skicka/gdrive
src/github.com/google/skicka/gdrive/upload.go:98: undefined: googleapi.SetOpaque
```

**Comment by mimium** [comment]
Exactly. The same situation here. Any solution?

**Comment by mmp** [comment]
It looks like everything works fine with that call removed (it seems that
it was added to work-around a long-standing bug in go's net/http package.)

I've pushed a commit with that fixed, if you sync to top of tree, it should
compile and run correctly. Let me know how it goes!

Thanks,
Matt
