### ISSUE TITLE
could i use skicka with no browser system?

### ISSUE THREAD

**Issue by uinz** [google/skicka#108]
i try to use skicka in my vps service

but got this error`skicka: error with OAuth2 Authorization: Error opening URL in browser`

it seems that i can't use skicka with no browser system?

thanks

**Comment by mmp** [comment]
Try using `skicka -no-browser-auth`.

**Comment by uinz** [comment]
@mmp  i tried use -no-browser-auth

maby some error in my `~/.skicka.config`

**Comment by agoode** [comment]
skicka does work without using a browser.
