### ISSUE TITLE
Building currently fails with two errors

### ISSUE THREAD

**Issue by foolip** [google/skicka#110]
```
$ go get github.com/google/skicka
# golang.org/x/net/context/ctxhttp
go/src/golang.org/x/net/context/ctxhttp/ctxhttp_pre17.go:36: req.Cancel undefined (type *http.Request has no field or method Cancel)
# google.golang.org/api/googleapi
go/src/google.golang.org/api/googleapi/googleapi.go:289: u.RawPath undefined (type *url.URL has no field or method RawPath)
```

I'm not having much luck with Go today, unable to successfully install anything it seems :)

**Comment by tvierling** [comment]
Update your Go. url.URL.RawPath() and http.Request.Cancel() weren't added until 1.5.

**Comment by foolip** [comment]
Looks like I have 1.7.3 already, which version is this confirmed to work with?

**Comment by tvierling** [comment]
Are you sure you're building with 1.7.3? Check the command `go version` to see what version is in your `$PATH`. Those errors specifically indicate a build environment of 1.4.x or earlier.

**Comment by foolip** [comment]
Oh, sorry, this error was indeed from an older version, 1.3.3. (I was trying to build on my VPS to get around #109.)

**Comment by tvierling** [comment]
If you're in a pinch, a version built using 1.7.3 as of yesterday, for 32-bit x86 (will run on a 64-bit system just fine as long as 32-bit glibc is installed too) is here; this link will self-delete on Feb 1:

https://www.duh.org/skicka.gz

**Comment by sebdv** [comment]
shouldn't this be marked as closed?
