### ISSUE TITLE
OAuth error

### ISSUE THREAD

**Issue by kmarchand** [google/skicka#111]
When I run `skicka ls` it opens the browser but after clicking "Allow" I get an error:

```
skicka: attempting to launch browser to authorize.
(Re-run skicka with the -no-browser-auth option to authorize directly.)
skicka: error with OAuth2 Authorization: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error" : "invalid_request",
  "error_description" : "Could not determine client ID from request."
}
```

I then tried `skicka -no-browser-auth ls`, click "Allow", get the verification code and paste it in and then still get an error:

```
skicka: error with OAuth2 Authorization: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error" : "invalid_request",
  "error_description" : "Could not determine client ID from request."
}
```

Same result when using Terminal or iTerm2, with Safari, Chrome and Firefox.

go version go1.7.5 darwin/amd64
macOS Sierra 10.12.2

Any ideas?

**Comment by ghoulr** [comment]
Same issue, on linux and mac, with or without browsers.

**Comment by obiwanakin** [comment]
I also have this issue on Ubuntu 16.04.

**Comment by ErwinP** [comment]
Exactly the same problem as kmarchand, on a Raspberry Pi 3 running Rasbian.
- go version go1.5 linux/arm
- Linux raspberrypi 4.4.38-v7 armv7l GNU/Linux

Thanks in advance!

**Comment by DanielHSM** [comment]
Same issue here, on the same setup as ErwinP.
Any ideas?
Thanks.

**Comment by mmp** [comment]
Interesting. This worked fine on my system until I updated to the latest version of the golang.org/x/oauth2 package. Digging now.

**Comment by mmp** [comment]
I believe that this is a bug in that package, but need to finish chasing it down and file a bug report with them.

As a work-around, if you run:

```
% cd $GOPATH/src/golang.org/x/oauth2
% git checkout 314dd2c0bf3ebd592ec0d20847d27e79d0dbe8dd
% go install .
% cd ../../../github.com/google/skicka
% go install .
```

Then skicka should work again.

**Comment by obiwanakin** [comment]
Let me test it out. Will report back with findings

**Comment by mmp** [comment]
https://github.com/golang/oauth2/issues/220

**Comment by whaozl** [comment]
@mmp ,it works! thank you!

**Comment by GEverding** [comment]
Hi, tried to set up skicka (fresh install of golang-1.6 and skicka) today and go the above error. the fix worked for me but it seems like this is still a issue.

**Comment by mmp** [comment]
Happily, the fix has been applied in golang.org/x/oauth2. I've just confirmed that at top of tree, everything works as expected. Running:

```
% go get -u golang.org/x/oauth2
% cd $GOPATH/src/github/google/skicka
% go install .
```

Should fix things if you're running into this.
