### ISSUE TITLE
Unable to install skicka in ubuntu 16.4 server

### ISSUE THREAD

**Issue by bsudhir6** [google/skicka#113]
Hi I'm unable to install skicka in ubuntu when I execute go get github.com/skicka or similar command it just shows empty console in the next like. I did setup $GOPATH as mentioned in the document.

**Comment by mmp** [comment]
I believe that "no output" means that the command executed successfully. Is
there a skicka binary in your $GOPATH/bin directory?

Thanks,
Matt

**Comment by bsudhir6** [comment]
No matt. No output in the sense it's not returning to shell prompt back. It just stays empty and I had to use Ctrl+C to come out of it. And no there is no binary in $GOPATH folder. 

I was following - http://xatierlike.blogspot.in/2015/05/skicka-google-drive-command-line-tool.html to install skicka as I was not sure about $GOPATH setting mentioned in github page. PFA attached
![skicka errors](https://cloud.githubusercontent.com/assets/2923168/23733741/96872b56-04a0-11e7-8bbd-7c4c075a0483.png)

**Comment by mmp** [comment]
Does it work to install other packages with "go get"? What happens if you
run with the -v flag for verbose output?

go get -v github.com/google/skicka

?

**Comment by agoode** [comment]
Please reopen if this is still an issue.
