### ISSUE TITLE
ignore certain files (such as .swp)

### ISSUE THREAD

**Issue by tnguyen14** [google/skicka#118]
Is it possible to tell skicka to ignore `.swp` files?

**Comment by mmp** [comment]
In the ~/.skicka.config file, you can set "ignored-regexp" in the [upload]
section. (There should be some commented-out examples in the default config
file generated the first time.)

Thanks,
Matt

**Comment by tnguyen14** [comment]
Thank you. Setting it as below works:

```
ignored-regexp=".*\\.swp"
```
