### ISSUE TITLE
basic security question about drive authorization

### ISSUE THREAD

**Issue by matanster** [google/skicka#122]
Does authorizing Skicka in google drive authorize any scicka installation on any computer, or is it specific to the installation made on the computer where the authorization is taking place?

Thanks!!!

**Comment by mmp** [comment]
After authorizing skicka, the authorization tokens are saved in a file that is, by default, .skicka.tokencache.json, in the current user's home directory (set to have permissions to only be readable by the current user).  That can be overridden using the -tokencache command line flag.

To answer your specific question, it should only authorize the current user, for a single specific google account.
