### ISSUE TITLE
Request: skicka static binaries for Android (ARMv7)

### ISSUE THREAD

**Issue by babam86** [google/skicka#124]
Can you to provide static binaries for Android (ARMv7), I will use it on Android. 

Thanks.

**Comment by brentybh** [comment]
Simply install Go environment on your macOS/Windows/Linux/BSD then do cross compile
https://gist.github.com/eduncan911/68775dba9d3c028181e4

**Comment by agoode** [comment]
Hi,

This project does not provide binaries.
