### ISSUE TITLE
How to download shared files/folders?

### ISSUE THREAD

**Issue by partylana** [google/skicka#127]
How to download shared files/folders?

**Comment by mbelmadani** [comment]
A work-around I've used is to add the shared folder to your own drive first.

![shareddrive](https://user-images.githubusercontent.com/14117454/46375563-9e43f980-c648-11e8-872c-d552a66fc627.png)

Then you should be able to get a shareable link. Download with:

`skicka download https://drive.google.com/open?id=<RestOfYourLinkHere>`

I've last ran this in February 2018, so I'm not sure if this is still supported but I would give it a try.

**Comment by partylana** [comment]
cool hack. Thank you.

**Comment by hftf** [comment]
[Google removed](https://workspaceupdates.googleblog.com/2020/03/shortcuts-for-google-drive.html) "Add to My Drive" last year, so this no longer works. Now skicka seems to have no way at all to interface with "Shared with me" folders.
