### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by BanditJackpot** [google/skicka#130]
Hi,

Having followed the various steps to install go ([Following this guide](https://stackoverflow.com/questions/48348262/install-go-golang-on-raspbian)) and Skicka, i'm now presented with the following error whilst trying the go get command:

```
# google.golang.org/api/gensupport
go/src/google.golang.org/api/gensupport/media.go:340: req.GetBody undefined (type *http.Request has no field or method GetBody)
```

Any tips on what could be the issue?  I'm running go version go1.7.4 linux/arm

Many Thanks in advance.

**Comment by mmp** [comment]
I just tried installing skicka from scratch with an empty $GOPATH directory and couldn't reproduce this.

What happens if you run `go get -u github/google/skicka`? I'm wondering if some of the dependencies are out of date.

**Comment by AlexOwen** [comment]
I had this problem but updating from go 1.7.1 to 1.11.5 fixed it.
