### ISSUE TITLE
duplicate file found on Google Drive

### ISSUE THREAD

**Issue by syoyo** [google/skicka#18]
skicka reports an following error if the folder on Google Drive has multiple files with the same filename.

```
$ skicka ls /
skicka: /myfile.txt: duplicate file found on Google Drive
```

This is expected behaviour as commented in skicka.go.

```
            // This shouldn't happen in principle, but Drive does
            // allow multiple files to have the same title. It's not
            // obvious how to reconcile this with Unix file
            // semantics, so we just disallow it entirely.
```

It would be also better to describe about this in README.

**Comment by pnu** [comment]
> So I don't know. We could fix it so ls() works, and so that individual file operations can specify a file ID. I think that would at least provide some benefit (as you would relegate the error to upload/download scenarios).

:+1: this, and upload option to overwrite (eg. `-f`), if identical path exists.

I'm using skicka to migrate a large collections of files to Drive. The transfer can take days (most time consuming is the creation of the folder structure and large number of small files - unfortunately, making a tar etc package is not an option in my use-case.)

After a failure (it happens), there are always multiple duplicate files left in Drive folders (*), so in practice I have to start a new upload, which is less than optimal. Also, it would be great if the default behaviour for duplicates in download (or upload, when it's listing the files to determine what to upload - this alone can take a very long time in my use-case) would be to warn (ie. skip the duplicate file) and not abort the transfer. Then it would be up to the user to resolve the discrepancy for the skipped files, by specifying the ids or by using other tools.

(*) I'm not sure _why_ there are duplicate files after a failure. However, I can easily see many scenarios, where duplicate files exist anyway, for some other reason external to skicka.

**Comment by mmp** [comment]
Everything should now be fairly reasonable w.r.t. duplicated files: things like ls and du just accept them without complaint, and upload and download go about their business while just ignoring any duplicates (and issuing warnings about them along the way.)
