### ISSUE TITLE
main.syncFileUp: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dantreble** [google/skicka#41]
It is 100% reproducible for this particular directory. Oddly it leaves me with duplicate files afterwards, I'm not sure if that is a symptom or cause. I'll look up how to do a debug build and get a better call stack if that would be useful?

dan@georgeiii:~$ skicka upload /srv/samba/photos/Pictures/2011/ /Pictures/2011/
skicka: Getting list of files to upload... Done. Starting upload.
342.02 MB / 4.43 GB [===>-------------------------------------] 7.54 % 40h38m36spanic: runtime error: invalid memory address or nil pointer dereference
signal 0xb code=0x1 addr=0x10 pc=0x40bdc1]

goroutine 12 [running]:
runtime.panic(0x6d57a0, 0xa6cde8)
        /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.syncFileUp(0xc2104a3040, 0x37, 0xc21048f990, 0x26, 0x7fad8bef9540, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:1387 +0xe01
main.func·002()
        /home/dan/go/src/github.com/google/skicka/skicka.go:1508 +0x1f8
created by main.syncHierarchyUp
        /home/dan/go/src/github.com/google/skicka/skicka.go:1520 +0xbbd

goroutine 1 [chan send]:
main.syncHierarchyUp(0x7fff434b433b, 0x1f, 0x7fff434b435c, 0xe, 0xc2100790c0, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:1526 +0xcbc
main.upload()
        /home/dan/go/src/github.com/google/skicka/skicka.go:2524 +0x516
main.main()
        /home/dan/go/src/github.com/google/skicka/skicka.go:2646 +0xa5b

goroutine 3 [syscall]:
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1394
goroutine 7 [sleep]:
time.Sleep(0x7735940)
        /usr/lib/go/src/pkg/runtime/time.goc:31 +0x31
main.func·001()
        /home/dan/go/src/github.com/google/skicka/skicka.go:182 +0xc1
created by main.launchBandwidthTask
        /home/dan/go/src/github.com/google/skicka/skicka.go:184 +0x71

goroutine 5 [IO wait]:
net.runtime_pollWait(0x7fad8befa880, 0x72, 0x0)
        /usr/lib/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc210052df0, 0x72, 0x7fad8bef90e8, 0xb)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc210052df0, 0xb, 0x7fad8bef90e8)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc210052d90, 0xc2101ee000, 0x1000, 0x1000, 0x0, ...)
        /usr/lib/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc2100005f8, 0xc2101ee000, 0x1000, 0x1000, 0x422d9f, ...)
        /usr/lib/go/src/pkg/net/net.go:122 +0xc5
crypto/tls.(*block).readFromUntil(0xc210079540, 0x7fad8befa9d8, 0xc2100005f8, 0x5, 0xc2100005f8, ...)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:459 +0xb6
crypto/tls.(*Conn).readRecord(0xc21005b500, 0x17, 0x0, 0x8)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:539 +0x107
crypto/tls.(*Conn).Read(0xc21005b500, 0xc2101b9000, 0x1000, 0x1000, 0x0, ...)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:897 +0x135
bufio.(*Reader).fill(0xc2101db660)
        /usr/lib/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).Peek(0xc2101db660, 0x1, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/pkg/bufio/bufio.go:119 +0xcb
net/http.(*persistConn).readLoop(0xc210061600)
        /usr/lib/go/src/pkg/net/http/transport.go:687 +0xb7
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/pkg/net/http/transport.go:528 +0x607

goroutine 6 [sleep]:
time.Sleep(0x5f5e100)
        /usr/lib/go/src/pkg/runtime/time.goc:31 +0x31
main.RateLimitedReader.Read(0x7fad881a0c38, 0xc2102a1160, 0xc2101951d8, 0xe28, 0xe28, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:214 +0x1bc
main.(*RateLimitedReader).Read(0xc210784b10, 0xc2101951d8, 0xe28, 0xe28, 0x1d8, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:1 +0xb3
io.(*multiReader).Read(0xc2102a1820, 0xc2101951d8, 0xe28, 0xe28, 0x1d8, ...)
        /usr/lib/go/src/pkg/io/multi.go:13 +0xa2
io/ioutil.(*nopCloser).Read(0xc210784b50, 0xc2101951d8, 0xe28, 0xe28, 0x1d8, ...)
        /usr/lib/go/src/pkg/io/ioutil/blackhole.go:1 +0x68
io.(*LimitedReader).Read(0xc2102a1f80, 0xc2101951d8, 0xe28, 0xe28, 0x1d8, ...)
        /usr/lib/go/src/pkg/io/io.go:398 +0xbb
bufio.(*Writer).ReadFrom(0xc210238500, 0x7fad8bf04350, 0xc2102a1f80, 0x6063072, 0x0, ...)
        /usr/lib/go/src/pkg/bufio/bufio.go:622 +0x15a
io.Copy(0x7fad8bf042b0, 0xc210238500, 0x7fad8bf04350, 0xc2102a1f80, 0x0, ...)
        /usr/lib/go/src/pkg/io/io.go:348 +0x124
net/http.(*transferWriter).WriteBody(0xc210adc460, 0x7fad8bf042b0, 0xc210238500, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/http/transfer.go:196 +0x57c
net/http.(*Request).write(0xc21067a5b0, 0x7fad8bf042b0, 0xc210238500, 0x0, 0xc21088cc60, ...)
        /usr/lib/go/src/pkg/net/http/request.go:400 +0x7e4
net/http.(*persistConn).writeLoop(0xc210061600)
        /usr/lib/go/src/pkg/net/http/transport.go:797 +0x185
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/pkg/net/http/transport.go:529 +0x61e

goroutine 9 [sleep]:
time.Sleep(0xbebc200)
        /usr/lib/go/src/pkg/runtime/time.goc:31 +0x31
github.com/cheggaaa/pb.(*ProgressBar).writer(0xc210cc6a50)
        /home/dan/go/src/github.com/cheggaaa/pb/pb.go:332 +0x48
created by github.com/cheggaaa/pb.(*ProgressBar).Start
        /home/dan/go/src/github.com/cheggaaa/pb/pb.go:101 +0x70

goroutine 10 [select]:
net/http.(*persistConn).roundTrip(0xc210061600, 0xc210784b90, 0xc210061600, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/http/transport.go:879 +0x6d6
net/http.(*Transport).RoundTrip(0xc210061200, 0xc21067a5b0, 0xd, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/http/transport.go:187 +0x391
code.google.com/p/goauth2/oauth.(*Transport).RoundTrip(0xc21001e4e0, 0xc21067a5b0, 0xc210784b10, 0x1550f6cd, 0xc21067a4e0)
        /home/dan/go/src/code.google.com/p/goauth2/oauth/oauth.go:296 +0x10f
main.uploadFileContents(0xc210c3bdc0, 0x7fad881a0c38, 0xc2102a1160, 0x1550f6cd, 0x0, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:1040 +0x115
main.syncFileUp(0xc21048e540, 0x37, 0xc21048f060, 0x26, 0x7fad8bef9540, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:1376 +0xc2f
main.func·002()
        /home/dan/go/src/github.com/google/skicka/skicka.go:1508 +0x1f8
created by main.syncHierarchyUp
        /home/dan/go/src/github.com/google/skicka/skicka.go:1520 +0xbbd

goroutine 11 [select]:
net/http.(*persistConn).roundTrip(0xc210c92600, 0xc210778100, 0xc210c92600, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/http/transport.go:879 +0x6d6
net/http.(*Transport).RoundTrip(0xc210061200, 0xc21067aa90, 0xd, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/http/transport.go:187 +0x391
code.google.com/p/goauth2/oauth.(*Transport).RoundTrip(0xc21001e4e0, 0xc21067aa90, 0xc210780630, 0x61600c9, 0xc21067a9c0)
        /home/dan/go/src/code.google.com/p/goauth2/oauth/oauth.go:296 +0x10f
main.uploadFileContents(0xc210c3c340, 0x7fad881a0c38, 0xc21031e260, 0x61600c9, 0x0, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:1040 +0x115
main.syncFileUp(0xc21049ff40, 0x37, 0xc21048f930, 0x26, 0x7fad8bef9540, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:1376 +0xc2f
main.func·002()  
        /home/dan/go/src/github.com/google/skicka/skicka.go:1508 +0x1f8
created by main.syncHierarchyUp
        /home/dan/go/src/github.com/google/skicka/skicka.go:1520 +0xbbd

goroutine 13 [select]:
net/http.(*persistConn).roundTrip(0xc210c92680, 0xc210780e40, 0xc210c92680, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/http/transport.go:879 +0x6d6
net/http.(*Transport).RoundTrip(0xc210061200, 0xc21067a750, 0xd, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/http/transport.go:187 +0x391
code.google.com/p/goauth2/oauth.(*Transport).RoundTrip(0xc21001e4e0, 0xc21067a750, 0xc210780dc0, 0x9fe9cad, 0xc21067a680)
        /home/dan/go/src/code.google.com/p/goauth2/oauth/oauth.go:296 +0x10f
main.uploadFileContents(0xc210c3c8c0, 0x7fad881a0c38, 0xc2100a2740, 0x9fe9cad, 0x0, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:1040 +0x115
main.syncFileUp(0xc2105f8340, 0x37, 0xc2104adab0, 0x26, 0x7fad8bef9540, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:1376 +0xc2f
main.func·002()
        /home/dan/go/src/github.com/google/skicka/skicka.go:1508 +0x1f8
created by main.syncHierarchyUp
        /home/dan/go/src/github.com/google/skicka/skicka.go:1520 +0xbbd

goroutine 19 [runnable]:
net/http.(*persistConn).readLoop(0xc210c92780)
        /usr/lib/go/src/pkg/net/http/transport.go:778 +0x68f
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/pkg/net/http/transport.go:528 +0x607

goroutine 21 [IO wait]:
net.runtime_pollWait(0x7fad8befa688, 0x72, 0x0)
        /usr/lib/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc210bcbfb0, 0x72, 0x7fad8bef90e8, 0xb)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc210bcbfb0, 0xb, 0x7fad8bef90e8)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc210bcbf50, 0xc2105f9000, 0x1000, 0x1000, 0x0, ...)
        /usr/lib/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc210846820, 0xc2105f9000, 0x1000, 0x1000, 0x422d9f, ...)
        /usr/lib/go/src/pkg/net/net.go:122 +0xc5
crypto/tls.(*block).readFromUntil(0xc2108c27b0, 0x7fad8befa9d8, 0xc210846820, 0x5, 0xc210846820, ...)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:459 +0xb6
crypto/tls.(*Conn).readRecord(0xc2101bbc80, 0x17, 0x0, 0x8)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:539 +0x107
crypto/tls.(*Conn).Read(0xc2101bbc80, 0xc210853000, 0x1000, 0x1000, 0x0, ...)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:897 +0x135
bufio.(*Reader).fill(0xc210b5a720)
        /usr/lib/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).Peek(0xc210b5a720, 0x1, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/pkg/bufio/bufio.go:119 +0xcb
net/http.(*persistConn).readLoop(0xc210c92680)
        /usr/lib/go/src/pkg/net/http/transport.go:687 +0xb7
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/pkg/net/http/transport.go:528 +0x607

goroutine 17 [IO wait]:
net.runtime_pollWait(0x7fad8befa7d8, 0x72, 0x0)
        /usr/lib/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc210bcbed0, 0x72, 0x7fad8bef90e8, 0xb)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc210bcbed0, 0xb, 0x7fad8bef90e8)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc210bcbe70, 0xc2109dbc00, 0x400, 0x400, 0x0, ...)
        /usr/lib/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc2108467c0, 0xc2109dbc00, 0x400, 0x400, 0x422d9f, ...)
        /usr/lib/go/src/pkg/net/net.go:122 +0xc5
crypto/tls.(*block).readFromUntil(0xc210928ba0, 0x7fad8befa9d8, 0xc2108467c0, 0x5, 0xc2108467c0, ...)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:459 +0xb6
crypto/tls.(*Conn).readRecord(0xc2101bba00, 0x17, 0x0, 0x8)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:539 +0x107
crypto/tls.(*Conn).Read(0xc2101bba00, 0xc2103a5000, 0x1000, 0x1000, 0x0, ...)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:897 +0x135
bufio.(*Reader).fill(0xc210b5a4e0)
        /usr/lib/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).Peek(0xc210b5a4e0, 0x1, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/pkg/bufio/bufio.go:119 +0xcb
net/http.(*persistConn).readLoop(0xc210c92600)
        /usr/lib/go/src/pkg/net/http/transport.go:687 +0xb7
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/pkg/net/http/transport.go:528 +0x607

goroutine 18 [sleep]:
time.Sleep(0x5f5e100)
        /usr/lib/go/src/pkg/runtime/time.goc:31 +0x31
main.RateLimitedReader.Read(0x7fad881a0c38, 0xc21031e260, 0xc21043290f, 0x6f1, 0x6f1, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:214 +0x1bc
main.(*RateLimitedReader).Read(0xc210780630, 0xc21043290f, 0x6f1, 0x6f1, 0x90f, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:1 +0xb3
io.(*multiReader).Read(0xc2105741a0, 0xc21043290f, 0x6f1, 0x6f1, 0x90f, ...)
        /usr/lib/go/src/pkg/io/multi.go:13 +0xa2
io/ioutil.(*nopCloser).Read(0xc2107780c0, 0xc21043290f, 0x6f1, 0x6f1, 0x90f, ...)
        /usr/lib/go/src/pkg/io/ioutil/blackhole.go:1 +0x68
io.(*LimitedReader).Read(0xc210574460, 0xc21043290f, 0x6f1, 0x6f1, 0x90f, ...)
        /usr/lib/go/src/pkg/io/io.go:398 +0xbb
bufio.(*Writer).ReadFrom(0xc210915bc0, 0x7fad8bf04350, 0xc210574460, 0x4dcb7a9, 0x0, ...)
        /usr/lib/go/src/pkg/bufio/bufio.go:622 +0x15a
io.Copy(0x7fad8bf042b0, 0xc210915bc0, 0x7fad8bf04350, 0xc210574460, 0x0, ...)
        /usr/lib/go/src/pkg/io/io.go:348 +0x124
net/http.(*transferWriter).WriteBody(0xc210adcb60, 0x7fad8bf042b0, 0xc210915bc0, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/http/transfer.go:196 +0x57c
net/http.(*Request).write(0xc21067aa90, 0x7fad8bf042b0, 0xc210915bc0, 0x0, 0xc2107f8180, ...)
        /usr/lib/go/src/pkg/net/http/request.go:400 +0x7e4
net/http.(*persistConn).writeLoop(0xc210c92600)
        /usr/lib/go/src/pkg/net/http/transport.go:797 +0x185
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/pkg/net/http/transport.go:529 +0x61e

goroutine 20 [select]:
net/http.(*persistConn).writeLoop(0xc210c92780)
        /usr/lib/go/src/pkg/net/http/transport.go:791 +0x271
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/pkg/net/http/transport.go:529 +0x61e

goroutine 22 [sleep]:
time.Sleep(0x5f5e100)
        /usr/lib/go/src/pkg/runtime/time.goc:31 +0x31
main.RateLimitedReader.Read(0x7fad881a0c38, 0xc2100a2740, 0xc21069843a, 0xbc6, 0xbc6, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:214 +0x1bc
main.(*RateLimitedReader).Read(0xc210780dc0, 0xc21069843a, 0xbc6, 0xbc6, 0x43a, ...)
        /home/dan/go/src/github.com/google/skicka/skicka.go:1 +0xb3
io.(*multiReader).Read(0xc2100ad640, 0xc21069843a, 0xbc6, 0xbc6, 0x43a, ...)
        /usr/lib/go/src/pkg/io/multi.go:13 +0xa2
io/ioutil.(*nopCloser).Read(0xc210780e00, 0xc21069843a, 0xbc6, 0xbc6, 0x43a, ...)
        /usr/lib/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc2108397b0, 0xc210cc5000, 0x1000, 0x1000, 0x10702660, ...)
        /usr/lib/go/src/pkg/net/net.go:122 +0xc5
crypto/tls.(*block).readFromUntil(0xc21060f300, 0x7fad8befa9d8, 0xc2108397b0, 0x5, 0xc2108397b0, ...)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:459 +0xb6
crypto/tls.(*Conn).readRecord(0xc2101bb780, 0x17, 0x0, 0x8)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:539 +0x107
crypto/tls.(*Conn).Read(0xc2101bb780, 0xc2108fd000, 0x1000, 0x1000, 0x0, ...)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:897 +0x135
bufio.(*Reader).fill(0xc210702660)
        /usr/lib/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).Peek(0xc210702660, 0x1, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/pkg/bufio/bufio.go:119 +0xcb
net/http.(*persistConn).readLoop(0xc210b10f00)
        /usr/lib/go/src/pkg/net/http/transport.go:687 +0xb7
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/pkg/net/http/transport.go:528 +0x607

goroutine 124 [select]:
net/http.(*persistConn).writeLoop(0xc210b10f00)
        /usr/lib/go/src/pkg/net/http/transport.go:791 +0x271
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/pkg/net/http/transport.go:529 +0x61e

dan@georgeiii:~$ skicka upload /srv/samba/photos/Pictures/2011/ /Pictures/2011/
skicka: Getting list of files to upload... skicka: /Pictures/2011/2011-01-11/MVI_6685.MOV: duplicate file found on Google Drive

**Comment by mmp** [comment]
There was (briefly) a bug that manifested itself like that for some of the error paths when uploading files. (And it was fixed in 107aeae9020985e21bb12f4f7fc5e76e130777dd on Dec 23.) Can you make sure you have the latest version?

If you're still seeing that, a run with '-debug' would be helpful to figure out which file is causing that to hit.

I believe that the duplicate files are unrelated (but will dig into that general issue now..)

**Comment by dantreble** [comment]
Latest gets past that point, I must have been unlucky and synced the broken version. Thanks
