### ISSUE TITLE
'rm' hangs on exit

### ISSUE THREAD

**Issue by kassai** [google/skicka#43]
Both 'rm' and 'rm -r' always hangs (for me) and needs to be stopped with CTRL-C. The intended content is however correctly deleted.

kassai@box:/media/photos$ skicka -debug -verbose rm /backup/katalog/testfil
^Ckassai@box:/media/photos$ skicka -debug -verbose rm -r /backup/katalog/
^C

I run it inside of GNU screen and am logged in to my Gdrive through a web browser while executing the code (I have a hard time seeing that it'd be relevant).

**Comment by mmp** [comment]
Ah, interesting. It was falling into an error handling path that did exponential backoff (which made it appear to hang.)

Fixed in 83c601d495248e029056d8edd237aeeac048388e

**Comment by mmp** [comment]
(And sorry for any trouble!)

**Comment by kassai** [comment]
No trouble, huge thanks for fixing this so quickly and for creating such a great tool!
