### ISSUE TITLE
error when download - undefined: strings.TrimSuffix

### ISSUE THREAD

**Issue by julian384** [google/skicka#44]
After running the command: go build github.com/google/skicka

I get the following:
    # github.com/google/skicka
    /usr/lib/go/src/pkg/github.com/google/skicka/skicka.go:2065: undefined: strings.TrimSuffix

Using Ubuntu 13 32-bit server via SSH from a Chromebook

**Comment by mmp** [comment]
It looks like you may have an old version of go installed. What does it say if you run

```
% go version
```
?

I believe that TrimSuffix was added in go 1.1 (release in March 2012).
