### ISSUE TITLE
Usage of ls -ll

### ISSUE THREAD

**Issue by kassai** [google/skicka#50]
It is great to be able to extract MD5 checksums with "ls -ll". I After uploading files, I use "ls -ll" to compare the gdrive checksums with local hashes dumped with "md5deep -l".

Comparing the checksums from the uploaded files with the list generated by md5deep is a non-trivial exercise for me. I use sed, cut, grep and some regexp magic to present a usable list from "ls -ll" output, that can be compared to the "md5deep" output.

Is there an easier way to achieve this?

**Comment by mmp** [comment]
I don't have any great ideas about what skicka could to do make this easier--the filename and md5 values are right there ready to be extracted. Do you have any ideas?

One thing that might help a bit is to also use the '-r' argument to ls, which makes it automatically recurse down into directories from the base directory you give it.
