### ISSUE TITLE
panic: Drive path . doesn't start with base path / prefix!

### ISSUE THREAD

**Issue by bdklahn** [google/skicka#65]
This happens when I try to download from the gdrive root. 
$ skicka download / localdir
So it makes sense that line 268 in download.go wouldn't get triggered, and will leave the '/' there, but . . .

I wonder if this has anything to do with . . .

commit a85631d3db516779048ea3fc9e1904bc180851e1
Author: Matt Pharr <mpharr@google.com>
Date:   Mon Apr 6 17:46:19 2015 -0700

    Name the root directory "." rather than “/“.
    
    (Simplifies a bit of code)

**Comment by mmp** [comment]
Fixed (I think). Please confirm!

**Comment by bdklahn** [comment]
commit 60d24dcb13e7740f2b1e5fa14a2b70525f4a2fef
. . . does appear to have fixed this, for me.

Thanks
