### ISSUE TITLE
Switch for silent upload

### ISSUE THREAD

**Issue by qeqar** [google/skicka#70]
hello,

is there a switch to prevent output?
i want do get rid the verbose upload output without using 2/dev/null.
which will also drop any error messages!

thanks in advanced,
mark

ps. if not it will be a feature request ;-)

**Comment by mmp** [comment]
There isn't a switch to do that, but it'd be fairly easy to add. This is probably a good excuse to generally revisit all of the output code, clean up the overall approach. (Will try to do this soon.)

**Comment by mmp** [comment]
Ok, you can now do things like `skicka -quiet upload /foo /bar` and see no output (unless there's an error along the way).  Let me know if I missed anything.

**Comment by qeqar** [comment]
i will start to test and let you know.

thanks for the fast implementation.
mark

**Comment by qeqar** [comment]
thanks looks good.

mark
