### ISSUE TITLE
Modification time comparison fails on Windows

### ISSUE THREAD

**Issue by bgrainger** [google/skicka#76]
Google Drive appears to have millisecond resolution for its file modification times, but NTFS supports nanosecond resolution. Thus `localTime.Equal(driveTime)` in [upload.go:559](https://github.com/google/skicka/blob/e3b04b1f7b4af333704c0e4be0f6266617daa9df/upload.go#L559) almost always returns `false` on NTFS, causing all files to go through an expensive checksum comparison.

Without objection, I will open a PR solving this by rounding all times to the nearest millisecond (i.e., `stat.ModTime().UTC().Round(time.Millisecond)`).

**Comment by bgrainger** [comment]
I think `Truncate` would actually be better (and should match what is implicitly happening in the current code).

**Comment by mmp** [comment]
Wow, nice find. That sounds like a good fix; I'd be happier taking it as a pull request if you're up for that in that I can't easily test it here, so would be glad to know that the fix actually worked!
