### ISSUE TITLE
Which Api is used

### ISSUE THREAD

**Issue by qeqar** [google/skicka#81]
hi,

i got a google notification that i use some deprecated Api: [URGENT Action Required] Your Google Apps account is using the discontinued Documents List API 

the only tool im aware of we using is skicka, so which ape did you use?

thanks in avanced,
mark

**Comment by mmp** [comment]
Hm, interesting. Skicka definitely does not use the Documents List API; it just uses the Drive API, so there shouldn't be any problems from the Documents List API going away.

It's possible that the application client id that you created from https://console.developers.google.com for skicka had usage of that API enabled (though skicka doesn't use it.)  FWIW in the next day or so an update to skicka will land that moves away from user-created client ids to a skicka-specific one, which would address this if that's the case.

**Comment by qeqar** [comment]
ok, thanks for the info.

i will look in our console if the old api is enabled.

mark
