### ISSUE TITLE
Feature Request: Bandwidth Limit

### ISSUE THREAD

**Issue by rabeyer** [google/skicka#94]
It would be quite useful to be able to limit the bandwidth usage of an upload. This might also assist in reducing the occurrence of rate limit exceeded errors where big Internet pipes are in use.

If you really want to get crazy, there could be a day/time of day table that would throttle uploads during work hours and open the "floodgates" at night and weekends.

**Comment by mmp** [comment]
FWIW you can set global bandwidth limits in the ~/.skicka.config file (if not time-limited bandwidth limits):

```
[upload]
        bytes-per-second-limit=524288  ; 512 kB/s
```

**Comment by rabeyer** [comment]
That's great!  Duh! Didn't think to look there! Thanks for the info. Guess I should read the manual (LOL).

**Comment by rabeyer** [comment]
Thanks again...P.S.-- It would be nice to be able to change the setting via a command line parameter. That way, it would be easy to accommodate schedules. Just a thought for the future.Rich B.


-------- Original Message --------
Subject: Re: [skicka] Feature Request: Bandwidth Limit (#94)
