### ISSUE TITLE
go get github.com/google/skicka fails

### ISSUE THREAD

**Issue by paulhybryant** [google/skicka#96]
The import code.google.com/p/go.crypto/pbkdf2 doesn't seem to be valid any more
in skicka.go

**Comment by ximellon** [comment]
Use this new package, [crypto](https://godoc.org/golang.org/x/crypto), in sub-repositories to replace the old one.

You should be able to get it with command:

    go get crypto

And replace the package name in import statements with `"golang.org/x/crypto/pbkdf2"`.

P.S. Tough gcfg is still available from Google Code (only warning appears), they also move to a new place, where you can find out from their Google Code page. And you can use `"code.google.com/p/gcfg"` to replace the old one. Cheers!

**Comment by mmp** [comment]
Fixed--thanks!
