### ISSUE TITLE
error creating Google Drive client: gob: encoder: message too big

### ISSUE THREAD

**Issue by Namke** [google/skicka#98]
Today I experienced this issues while skicka try updating metadata cache, at some point it is stop and just spawn this message "error creating Google Drive client: gob: encoder: message too big"
This issues happen both in Windows and Mac, with go 1.5.2 installed.
Google around it seem internal issues of go and should be work around it for now.

**Comment by mmp** [comment]
Interesting! Do you have a large number of files / folders in Drive? That error is occurring when skicka attempts to serialize the cache of metadata about the files stored in Drive and store it on disk.

I reported this as a bug to the Go folks (https://github.com/golang/go/issues/13850); we'll see what they say.

It would be fairly straightforward to work around this in skicka, though it'd require changing the serialization format for the metadata, which would be nice to avoid if possible. So we'll see if a fix is imminent on the Go side, or if this is claimed to be working as intended (in which case we'll definitely fix it over here.)

**Comment by Namke** [comment]
I checked with Go beta version (1.6.x), both in Mac and Windows and it still happen, guess it is not fix in Go side yet.
My drive contain huge amount of files (not in term of size but in term of number of files), the cache file size is now over 1GB. And yes, it is happen at the end of updating metadata file so I guess it is happen due to serialize the metadata cache.

Would be helpful if there are option to just push file to drive without syncing (force upload perhaps), I experience the case when skicka cost more time on update/serialize metadata than actual uploading.

**Comment by mmp** [comment]
The fix just pushed should work-around the gloang issue from skicka. (Please let me know if it works!)

I opened issue #99 to track the request to not track/update metadata. I'll start looking through the code to think about what this would entail.

Thanks!

**Comment by Namke** [comment]
Just checked, it is work like a champ on both MacOS and Windows

Thanks!
